// Q # 1

// var variable1, variable2, variable3;


// Q # 2 

// egal variable names in JavaScript:

// Must start with a letter (a-z, A-Z), underscore (_), or dollar sign ($).
// Can contain letters, digits, underscores, or dollar signs.
// Cannot start with a number.
// Cannot use reserved keywords (like var, if, function, etc.).
// Cannot contain spaces or special characters except underscore (_).



// Q # 3 ?

// document.write("b) Variable names can only contain letters, digits, underscores, or dollar signs. For example $my_1stVariable<br>");

//         document.write("c) Variables must begin with a letter, underscore, or dollar sign. For example $name, _name, or name<br>");

//         document.write("d) Variable names are case-sensitive<br>");

//         document.write("e) Variable names should not be JavaScript reserved keywords");



